version: "3.9"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: backend:test
        container_name: medusa-server
        depends_on:
            - postgres
            - redis
        ports:
            - 9000:9000
            - 7001:7001
        volumes:
            - ./backend:/app/medusa
            - backend_node_modules:/app/medusa/node_modules
        environment:
            DATABASE_TYPE: postgres
            DATABASE_URL: postgres://admin:admin@postgres:5432/medusa_db
            REDIS_URL: redis://cache
            NODE_ENV: development
            JWT_SECRET: some_jwt_secret
            COOKIE_SECRET: some_cookie_secret
            MEDUSA_ADMIN_ONBOARDING_TYPE: default
            STORE_CORS: http://storefront:8000,http://localhost:7001

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    backend_node_modules:
