version: "3.9"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: backend:test
        container_name: medusa-server
        depends_on:
            - postgres
            - redis
        ports:
            - 9000:9000
            - 7001:7001
        environment:
            DATABASE_TYPE: postgres
            DATABASE_URL: postgres://admin:admin@postgres:5432/medusa_db
            REDIS_URL: redis://cache
            NODE_ENV: development
            JWT_SECRET: some_jwt_secret
            COOKIE_SECRET: some_cookie_secret
            MEDUSA_ADMIN_ONBOARDING_TYPE: default
            STORE_CORS: http://localhost:8000,http://localhost:7001

    postgres:
        image: postgres:16-alpine
        volumes:
            - postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=medusa_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432

    redis:
        image: redis
        container_name: cache
        expose:
            - 6379:6379

volumes:
    postgres-db:
