version: '3'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: dob-ecommerce-app:latest
        container_name: dob-ecommerce-server
        depends_on:
            - redis
        env_file:
            - ./backend/.env
        ports:
            - 9000:9000
            - 7001:7001
        volumes:
            - ./backend:/app
            - backend_node_modules:/app/node_modules
        environment:
            REDIS_URL: redis://cache

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    backend_node_modules:
