version: '3'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: dob-ecommerce-app:latest
        container_name: dob-ecommerce-server
        depends_on:
            - redis
            - postgres
        env_file:
            - ./backend/.env
        ports:
            - 9000:9000
        volumes:
            - ./backend:/app
            - backend_node_modules:/app/node_modules
        environment:
            REDIS_URL: redis://cache
            DATABASE_URL: postgres://admin:admin@postgres:5432/medusa_db

    postgres:
        image: postgres:16-alpine
        volumes:
            - postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=medusa_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    postgres-db:
    redis_data:
    backend_node_modules:
