version: '3.9'
services:
    postgres:
        image: postgres:16-alpine
        volumes:
        - postgres-db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=medusa_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        ports:
        - 5432:5432

    test-postgres:
        image: postgres:16-alpine
        volumes:
        - test-postgres-db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=test_medusa_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        ports:
        - "5433:5432"

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data

volumes:
    postgres-db:
    test-postgres-db:
    redis_data:
