import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, App } from "antd";
import "./globals.css";
import theme from "../theme";
import { cn } from "@/lib/utils";
import Header from "@/modules/common/components/header";
import { cache } from "react";
import { listCategories } from "@/actions/productCategory";
import { TTreeCategories } from "@/types/productCategory";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	manifest: "/manifest.json",
};

const fetchCategories = cache(async () => await listCategories());

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const categories = await fetchCategories();
	const getAncestors = (category) => {
		const convertedCategory = {
			id: category.id,
			label: category.name,
			key: category.handle,
		};

		if (
			category.category_children &&
			category.category_children.length > 0
		) {
			convertedCategory.children = category.category_children.map(
				(child) => getAncestors(child)
			);
		}

		return convertedCategory;
	};
	const formatCategories: TTreeCategories[] = categories?.map((category) =>
		getAncestors(category)
	) || null;

	return (
		<html lang="en">
			<body className={cn(inter.className, "w-full")}>
				<AntdRegistry>
					<ConfigProvider theme={theme}>
						<App>
							<Header categories={formatCategories} />
							{children}
						</App>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
