version: "3.9"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: dob/backend:v1
        container_name: dob-ecommerce-server
        env_file:
            - ./.env
        depends_on:
            - redis
        ports:
            - 9000:9000
            - 7001:7001
        volumes:
            - ./:/app
            - ./node_modules:/app/node_modules

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
